-- a1)
INSERT INTO
DEPARTMENT
VALUES
('Factory', 3, 999999999, '1200-03-12');

SELECT * FROM DEPARTMENT;

-- a2)
INSERT INTO
DEPARTMENT
VALUES
('Factory', NULL, 123456789, '1200-03-12');

SELECT * FROM DEPARTMENT;

-- a3)
INSERT INTO
DEPARTMENT
VALUES
('Factory', 5, 123456789, '1200-03-12');

SELECT * FROM DEPARTMENT;

-- a4)
INSERT INTO
WORKS_ON
VALUES
(123456789, 1, -2);

SELECT * FROM WORKS_ON;

-- a5)
INSERT INTO
WORKS_ON
VALUES
(123456789, 3, 12);

SELECT * FROM WORKS_ON;

-- a6)
INSERT INTO
DEPT_LOCATIONS
VALUES
(1, 'Dallas');

SELECT * FROM DEPT_LOCATIONS;

--  b)
INSERT INTO
DEPENDENT
VALUES
(123456789, 'LeBron', 'Male', '1912-02-02'),
(123456789, 'Bronny', 'Male', '1912-02-02'),
(123456789, 'Bryce', 'Male', '1912-02-02');

SELECT * FROM DEPENDENT;

-- c1)
INSERT INTO DEPT_LOCATIONS (Dnumber, Dlocation)
SELECT D.Dnumber, 'France'
FROM DEPARTMENT D
WHERE NOT EXISTS (
	SELECT 1
	FROM DEPT_LOCATIONS DL
	WHERE DL.Dnumber = D.Dnumber
	AND DL.Dlocation = 'France'
);

SELECT * FROM DEPT_LOCATIONS;

-- c2)
INSERT INTO EMPLOYEE
(Fname, Minit, Lname, Ssn, Bdate, Address, Sex, Salary, Super_ssn, Dno)
SELECT Fname, Minit, Lname, Ssn + 1, Bdate, Address, Sex, Salary, Super_ssn, Dno
FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

-- c3)
INSERT INTO WORKS_ON
SELECT Ssn, 1, 10
FROM EMPLOYEE E
WHERE NOT EXISTS (
	SELECT 1
	FROM WORKS_ON WO
	WHERE E.Ssn = WO.Essn
	AND Pno = 1
);

SELECT * FROM WORKS_ON;

-- d)
CREATE TABLE BOTTOM_EMPLOYEE AS
SELECT * FROM EMPLOYEE WHERE FALSE;

INSERT INTO BOTTOM_EMPLOYEE
SELECT * FROM EMPLOYEE WHERE Ssn < 500000000;

SELECT * FROM BOTTOM_EMPLOYEE;

-- e)
CREATE TABLE EMPLOYEE_RICH (LIKE EMPLOYEE INCLUDING ALL);

INSERT INTO EMPLOYEE_RICH
SELECT * FROM EMPLOYEE WHERE Salary > 30000;

SELECT * FROM EMPLOYEE_RICH;

-- f)
DELETE FROM DEPENDENT
WHERE Dependant_name = 'Bronny';

SELECT * FROM DEPENDENT;

-- g)
DELETE FROM DEPENDENT
WHERE Dependant_name IN ('Bronny', 'LeBron', 'Bryce');

SELECT * FROM DEPENDENT;

-- h)
DELETE FROM DEPARTMENT
WHERE Dnumber = 3;

SELECT * FROM DEPARTMENT;

-- i)
DELETE FROM DEPT_LOCATIONS
WHERE Dnumber IN 
(SELECT Dnumber FROM DEPARTMENT WHERE Dname = 'Reasearch');

SELECT * FROM DEPT_LOCATIONS;

-- j)
UPDATE EMPLOYEE
SET Lname = 'Curry', Sex = 'Male'
WHERE Dno = 5;

SELECT * FROM EMPLOYEE;

-- k)
UPDATE DEPARTMENT
SET Dname = 'CLOSED', Mgr_ssn = 123456789, Mgr_start_date = '2025-10-10'
WHERE Dname != 'Headquarters';

SELECT * FROM DEPARTMENT;

-- l)
UPDATE EMPLOYEE
SET Salary = Salary * 2
WHERE Ssn IN 
(SELECT Mgr_ssn FROM DEPARTMENT);

SELECT * FROM EMPLOYEE;
